### POST - Add a book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Spring Boot in Action",
  "author": "Craig Walls"
}

### GET - Get all books
GET http://localhost:8080/api/books
